name: Android CI Build

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js and pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      
      - name: Install project dependencies
        run: pnpm install

      - name: Build web assets
        run: pnpm build

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Cordova CLI
        run: npm install -g cordova

      - name: Copy web assets to Cordova www folder
        run: cp -r dist/* quick-guide-app/www/

      - name: Add Platform and Build Android APK
        run: |
          cd quick-guide-app
          cordova platform add android
          cordova build android --debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: quick-guide-app/platforms/android/app/build/outputs/apk/debug/app-debug.apk