name: Android CI Build

on:
  push:
    branches: [ "main", "master" ] # Triggers the workflow on push events to main or master branch
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js and pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      
      - name: Install project dependencies
        run: pnpm install

      - name: Build web assets
        run: pnpm build

      - name: Setup Cordova
        uses: cordova-actions/setup-cordova@v1
        with:
          cordova-version: 12.0.0

      - name: Copy web assets to Cordova www folder
        run: cp -r dist/* quick-guide-app/www/

      - name: Build Android APK
        run: |
          cd quick-guide-app
          cordova build android --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: quick-guide-app/platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk